wireapp/wire-ios-request-strategy

WireRequestStrategy/ZMContextChangeTracker.h, WireRequestStrategy/ZMLocallyModifiedObjectSet.h, WireRequestStrategy/ZMUpstreamRequest.h, WireRequestStrategy/ZMUpstreamTranscoder.h
During the Swift 3 migration of the sync-engine some files were modified, which have previously been extracted to this framework. This PR re-applies these changes.
=> Port changes made to to extracted files during the Swift 3 migration

WireRequestStrategy.xcodeproj/project.pbxproj, WireRequestStrategyTests/ZMChangeTrackerBootstrapTests.m, WireRequestStrategyTests/ZMSyncOperationSetTests.m
Two classes who was moved into this framework still had their corresponding tests in the `sync-engine`. This PR move them here.
=> Move missing test classes from sync-engine

WireRequestStrategy/ZMSingleRequestSync.h, WireRequestStrategy/ZMSingleRequestSync.m, WireRequestStrategyTests/ZMSingleRequestSyncTests.m
The `ZMSingleRequestSync` reported a progress state of `ZMSingleRequestInProgress ` even when the request was not actually being performed at the moment, which is why a new state `ZMSingleRequestProgressReady` has been introduced. Following the new states of a single request sync:
* Initially the state of a created `ZMSingleRequestSync` is `ZMSingleRequestIdle`.
* When `readyForNextRequest ` is called the state changes to `ZMSingleRequestReady`, requests can now be created by calling `nextRequest`.
* If a request gets created by the transcoder owning the sync the state changes to `ZMSingleRequestInProgress`, if not it changes to `ZMSingleRequestCompleted`.
* If the completion state is reset the sync returns to its initial state `ZMSingleRequestIdle`.
This change is needed as the …
=> Add `ready` state to ZMSingleRequestSync

WireRequestStrategy/Helper/AssetRequestFactory.swift
* The upload requests using the `/assets/v3` endpoint were not using the background `URLSession` and thus immediately terminated when the app was killed or the network connection lost.
=> Add method to create a background request for /asset/v3 uploads

WireRequestStrategy/ZMDependentObjects.h, WireRequestStrategy/ZMDependentObjects.m, WireRequestStrategy/ZMUpstreamInsertedObjectSync.m, WireRequestStrategy/ZMUpstreamModifiedObjectSync.m, WireRequestStrategy/ZMUpstreamTranscoder.h
There is no reason to restrict object dependency (dependency to resolve before they can be synchronized to the backend) to managed object. Any type of object could be a dependency.
=> Relax type constraint on dependency for objects

WireRequestStrategy/ZMDependentObjects.h, WireRequestStrategy/ZMDependentObjects.m, WireRequestStrategy/ZMUpstreamInsertedObjectSync.m, WireRequestStrategy/ZMUpstreamModifiedObjectSync.m, WireRequestStrategy/ZMUpstreamTranscoder.h
It has to be `id` to translate to `AnyObject` in Swift
=> Relax constraints even more

WireRequestStrategy/DependentObjects.swift
Currently in the debug logs for dependencies, it's not clear which dependency is cleaned. 
This PR adds the pointer to the object (it's easier said than done, in Swift) in those logs.
=> Add ptr to debug output for dependency

WireRequestStrategy/ZMRemoteIdentifierObjectSync.h
* We need to explicitly conform `ZMRemoteIdentifierObjectSync` to `ZMRequestGenerator` to avoid casting it when using it from Swift.
* Needed for https://github.com/wireapp/wire-ios-sync-engine/pull/381.
=> Conform ZMRemoteIdentifierObjectSync to ZMRequestGenerator protocol

WireRequestStrategy/ZMDownstreamObjectSync.h, WireRequestStrategy/ZMDownstreamObjectSync.m, WireRequestStrategy/ZMDownstreamObjectSyncWithWhitelist.m, WireRequestStrategyTests/ZMDownstreamObjectSyncTests.m
* In some cases we might not want to delete the object when `deleteObject:downStreamSync` is called on a `ZMDownstreamTranscoder`.
* We now pass the `ZMTransportResponse` down to the transcoder so that it can perform additional checks on the status code for example.
=> Forward the response to the downstream transcoder

Sources/Request Strategies/Assets/AssetClientMessageRequestStrategy.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewUploadRequestStrategy.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift
Add asserts to ensure the message sender is self. The only strategies where we can't assert this are the ones sending wrapped `ZMGenericMessage` objects directly (in the form of `GenericMessageEntity`) which don't have a sender property but on the other hand are also usually "fire and forget" messages, so they don't get stored when they are received.
=> Add asserts to ensure the message sender is self

Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoderTests.swift
It's been observed in rare circumstances that the iOS client re-sends a message from another user.
A message is only sent out if the `delivered` property is set to false, which should never be case the for received messages. However in theory a message could be received, the context saves and the app crashes before the `delivered` property has been updated to true.
-  Filter messages which do not have the sender equal to the self user.
- Mark a message immediately after creating it to prevent any saves happening in between.
=>  Add safe guards against sending out wrong message

Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategy.swift
We force-unwrapped the current operation queue from the factory method that creates the link preview strategy, which caused a crash when it was called outside of the context of an `NSOperation`.
If the current operation queue is not available, we use the main operation queue as a fallback.
=> Fix a crash when creating link preview strategy

Sources/Protocols/OTREntity.swift
We should save the context after setting the modified keys to trigger the fetch for the missing clients immediately.
Posting a `RequestsAvailableNotification` instead ought to do the trick, but strangely (and inexplicably) the observers didn't always receive the notification, even though the observers do not listen for notifications from a specific object, and the notifications aren't posted with a sender object. 
Even more strangely, the reason why saving the context works is because `ZMOperationLoop` in sync engine responds to the context save by posting its own `RequestsAvailableNotification`, which, as an observer of this notification, receives.
If anyone has an idea why this is, I'd love to hear it 😄
=> save context after modifiying keys to trigger fetch

Sources/Protocols/OTREntity.swift
SE tests gets stuck waiting for all groups to finish when a client is missing.
Doing a save will cause the operation loop to execute objectsDidChange on all context trackers. If a client is missing we will end up in `OTREntity.dependentObjectNeedingUpdateBeforeProcessingOTREntity` which always attempt to do:
```
selfClient.setLocallyModifiedKeys(Set(arrayLiteral: ZMUserClientMissingKey))
context.enqueueDelayedSave()
```
This will cause the operation loop to never to stop until the missing client is fetched.
Only update modified keys and save if the key is actually missing from the set.
=> Fix save loop

Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift
When a message is deleted by the sender, the local notification on the receiver side is not removed from the lock screen / Notification Center. 
Notification cancellation for deleted or edited messages is done by the `LocalNotificationDispatcher` in `process(genericMessage:)` (see [SyncEngine](https://github.com/wireapp/wire-ios-sync-engine/blob/f63ab47393404b044840ba37729f18379ed7dd60/Source/Notifications/Push%20notifications/LocalNotificationDispatcher%2BMessages.swift#L46)). The problem is, that update result created in this situation is nil (see [DataModel](https://github.com/wireapp/wire-ios-data-model/blob/c3da37dfa4d2053f7cac152a3808faf8da8d9cdb/Source/Model/Message/ZMOTRMessage.m#L173)). As a result, we return early, and the local notification dispatcher is not able to process the …
=> Process generic message for notifications first

Sources/Helpers/MessageExpirationTimer.swift
Image expire if they are read
Another case of not taking the new .read delivery state into account.
Also check for the read state.
As already mentioned in https://github.com/wireapp/wire-ios-data-model/pull/637 we should avoid these kind of bugs in the future. I think a good way would be to expose something like a `isDelivered` boolean which already exists on `ZMOTRMessage`. I'll not write a test for this now since I think we should re-factor this right away.
=> Fix read images expire after being sent

Sources/Request Strategies/Assets/AssetClientMessageRequestStrategy.swift
If file upload completes in the background the file is still showing as "in-progress" for the receiver.
We would upload the file correctly, but would not update the message with the uploaded asset identifier. It was happening because the request strategy dies not allow requests in the background.
Allow requests in the background.
=> Allow requests in background for asset client message

Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategy.swift, Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift
App would crash when timer runs out for an received ephemeral image.
We trigger an assertion `fatalError("Cannot generate request for ...)` when attempting to generate a request to download the asset but we can't, this scenario happens because:
1. UI requests file to be downloaded every time it re-configures the asset message, this happens when the file has finished downloading.
2. This will set `isDownloading = true` but  won't generate any requests since the download filter checks if the file is already downloaded
3. The ephemeral timer runs out and we obfuscate the message, deletes downloaded files and generic messages among others
4. Since the file no longer exists locally the download filter will pass attempt generate a request
5. It fails to generate the request since the generic …
=> Don't mark mark asset as isDownloading if asset is already downloaded

Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategy.swift
App was freezing when loading the image collection in Search UI. This was caused by multiple download operations triggered while scrolling; seems to be partially solved with the refactoring of the last week.
I've added a notification after the completion of the download that triggers `loadImage()` of  `CollectionImageCell`, because cells weren't notified about that.
=> ZIOS-11271: App freezes when loading image collections in Search UI

Sources/Request Strategies/Assets/V2/AssetV2DownloadRequestStrategy.swift
Downloading a broken V2 asset would trigger a request loop
Once a asset is whitelisted for downloading we will attempt to download over and over again until it succeeds, which it never happens since it's broken.
Check that `message.isDownloading` is true in the download filter predicate. We reset `isDownloading` to `false` when the request response arrives.
=> Fix V2 asset request loop

Sources/Request Strategies/Assets/AssetClientMessageRequestStrategy.swift, Sources/Request Strategies/Assets/AssetClientMessageRequestStrategyTests.swift
After applying asset transfer migration hotfix some assets come in an unexpected state which caused it to try and create requests for messages sent by others and expired messages.
This happens when the migration is applied twice, It will cause .failed message to be moved to the `.uploaded` state.
- Prevent sending of expired messages
- Prevent sending of message not created by self user
=> Prevent sending assets of other users & expired assets

Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategy.swift, Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift
App would crash after the ephemeral time runs out for an asset.
We would try do download the asset after the content has been deleted which triggered a fatal assert.
Don't attempt to download assets which are missing the `.uploaded` protobuf.
=> Don't attempt download assets without .uploaded in the protobuf

Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoderTests+MessageConfirmation.swift
We would send out multiple message delivery confirmations for incoming messages.
We recently implemented support for confirming message delivery in batches after all events have been processed but didn't remove the old message delivery confirming code in the `ClientMessageTranscoder`.
Remove the now obsolete code for confirming message deliveries in `ClientMessageTranscoder` and update the tests.
Since we no longer access any properties on  `ZMMessageUpdateResult in `ClientMessageTranscoder ` we simplify this API and return a ` ZMOTRMessage` . This will come in a separate PR.
=> Don't insert delivery confirmation when processing incoming message

Cartfile.resolved, WireRequestStrategy.xcodeproj/project.pbxproj
follow up of https://github.com/wireapp/wire-ios-sync-engine/pull/1016
=> move libPhoneNumber from data model to sync engine

Sources/Protocols/OTREntity.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategyTests.swift
The app would crash when force unwrapping the longer existing self client.
The self client is never including the list of missing clients and was therefore deleted.
Exclude self clients when parsing the empty message response since we will receive these updates through other events.
=> Crash on verifying legal hold

Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategy.swift, Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift
This PR solve the following edge case: when the back end redirects to the cloud service to get the image asset in a conversation, it could happen that the network bandwidth of the device is really rare. If the time interval is pretty long before the connectivity returns good the cloud responds with an error having status code 403
retry the image request and not delete the asset client message in case of status code 403.
=> [Fix] Retry download asset when Cloud server error is 403.

Sources/Request Strategies/Availability/AvailabilityRequestStrategy.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategyTests.swift
Currently we are not sending status updates if the team is above a certain size. This is direct conflict with the new status broadcast strategy, where we ensure status updates are sent to a specified maximum number of recipients.
Remove the code related to where the status should be communicated.
**JIRA:** https://wearezeta.atlassian.net/browse/ZIOS-12885
=> [Fix] Always communicate status

Sources/Request Strategies/Availability/AvailabilityRequestStrategy.swift
A method name was changed in https://github.com/wireapp/wire-ios-data-model/pull/945
=> [Fix] Update method name

Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategy.swift, Sources/Request Strategies/Assets/AssetV3DownloadRequestStrategyTests.swift, Sources/Request Strategies/Assets/AssetV3PreviewDownloadStrategy.swift
when the client was not able to decrypt an asset a request was done in loop.
when the asset could not be decrypted it will be deleted from the conversation.
=> [Feature]  Asset decryption error fix

Sources/Protocols/OTREntity.swift, Sources/Request Strategies/Base Strategies/OTREntityTranscoderTests.swift
We had an incident (internal) were encryption sessions broke, which resulted in decryption errors.
The session broke because the backend unexpectedly reported client as missing when they weren't due to mismatch between backend and client rollout. We the client was blindly trusting the server that client were missing and re-fetched the pre-keys and established new sessions, effectively breaking the sessions.
Even though this shouldn't happen when the client and backend is in sync but it still would  be nice to be resilient towards these kind of issues.
Verify that a client doesn't already have an established session before adding it to the list of missing clients.
=> [Fix] Don't mark clients with established sessions as missed

Sources/Helpers/ZMMessage+Dependency.swift, Sources/Protocols/OTREntity.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategy.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategyTests.swift, Sources/Request Strategies/Base Strategies/OTREntityTranscoderTests.swift, Sources/Request Strategies/Generic Message/GenericMessageRequestStrategy.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategy.swift
We already re-fetch user metadata when we discover that the last client of user is deleted when sending a message. In addition to that we also need to re-fetch the metadata when a user is reported as redundant when sending a message. 
Being redundant means that the user is no longer part of the conversation, which could mean that the user left the conversation and you missed the leave event or that the user has deleted his account and you missed the user deletion event. In either case we resolve it by re-fetching the conversation and the user metadata.
There's quite some code duplication going on here but fixing it would be too big of a task include in this PR. I'll create a separate re-factoring ticket for this.
=> [Feature] re-fetch redundant users in order to discover if they are deleted

Sources/Helpers/ZMMessage+Dependency.swift, Sources/Protocols/OTREntity.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategy.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategyTests.swift, Sources/Request Strategies/Base Strategies/OTREntityTranscoderTests.swift, Sources/Request Strategies/Generic Message/GenericMessageRequestStrategy.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategy.swift
This is a follow up on https://github.com/wireapp/wire-ios-request-strategy/pull/220 to remove some code duplication.
Parts of the business logic for handling redundant and missing clients was duplicated in all the objects implementing the `OTREntity` protocol
Add an optional `conversation: ZMConversation?` property to the`OTREntity` protocol and move the duplicated business logic into the protocol methods for parsing redundant and missing clients.
=> [Refactor] Remove code duplication when processing message sending responses

Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetDownloadRequestStrategy.swift
Unused `ZMLinkPreview` causes build error when objc protobufs are removed (using [this branch of wire-ios-protos](https://github.com/wireapp/wire-ios-protos/tree/refactor/remove-objc-message-proto))
Remove the extension since it is unused.
=> [Fix] Remove unused ZMLinkPreview extension

Sources/Request Strategies/Client Message/ClientMessageRequestFactory.swift, Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift
When sending a targeted message, the backend response with a 412 error stating there are missing clients.
The query parameter `ignore_missing` has no value specified.
Set the value to the parameter to `true`
=> [Fix] ignore_missing query parameter has no value

Sources/Protocols/PushMessageHandler.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift, Tests/Helpers/MockObjects.swift
When receiving a message we are scheduling duplicate notifications for messages
Since notifications for regular messages are now created directly from update events we should take care to only process events once otherwise we'll insert multiple notifications per message. This was happening in the `ClientMessageTranscoder` which forwarded all update events to notification dispatcher in order to cancel notifications for edited, deleted or hidden messages.
- Stop forward events to local notification dispatcher since this already happens in `ZMSyncStrategy+EventProcessing`
- Remove now no longer used method on the `PushMessageHandler` protocol
=> [Fix] Don't schedule duplicate notifications

Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategy.swift, Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategyTests.swift
The app is continuously sending delivery receipts.
We are sending delivery receipts for confirmation messages (aka delivery receipts), so if we send a delivery receipt, the other client will send a receipt for that receipt, for which we will send a receipt for that receipt...
Don't send receipts for confirmation messages.
=> [Fix] Don't send delivery receipts for confirmation messages

Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategy.swift
The predicate used to determine which `ZMClientMessage` instances require image processing is inefficient.
The predicate checks there exists any data in the asset cache for the given message. It does this by trying to read the data (in its entirety) and checking if it exists. This relatively slow because it has to read data from disk.
Use a more appropriate method that checks for the existence of data without actually reading it all.
=> [Performance] Use more efficient method to check existence of data in cache

Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift
There have been changes in the DM with the name of the public property. This PR alines the name of the property.
Needs releases with:
- [ feature/feature-configuration-main ]
=> [Fix] FeatureConfigRequestStrategy: rename property

Sources/Helpers/EncryptionSessionDirectory+UpdateEvents.swift
The app would crash upon receiving a message which is marked as transient and can't be decrypted.
We ignore the timestamp for transient update events so that property will return `nil`. When we try to add the "Decryption Failed" system message we force unwrap the timestamp and crash.
Don't force unwrap the timestamp since `appendDecryptionFailedSystemMessage()` accepts an optional timestamp.
=> [Fix] Don't force unwrap optional timestamp

Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategy.swift
The client fetching strategy wouldn't run after the changes made in https://github.com/wireapp/wire-ios-sync-engine/pull/1408
We now correctly report the sync state to `.waitingForWebsocket` but the strategies weren't configured to run in that state.
Allow all strategies to run in `.waitingForWebsocket` if they are already allowed to run during the quick sync.
=> [Fix] Some strategies not running while waiting for the web socket

Sources/Payloads/Payload+Processing.swift, Sources/Payloads/Payload.swift
Message can't be sent in a conversation which contains a client which doesn't have its deviceClass defined.
`deviceClass` was annotated as non-optional which causes us to reject the whole response when fetching client metadata which contains a client which doesn't have the device class set.
Mark the `deviceClass` as optional. This will allow us to process all the clients with an assigned device class and do nothing when it's missing.
=> [Fix] deviceClass was incorrectly marked as non-optional

Sources/Helpers/EncryptionSessionDirectory+UpdateEvents.swift
When a new client posts a message in a verified conversation, there is no indication that this is a new client.
Since we have information about the new client when decrypting events, we can also update the security level at this point.(add `updateSecurityLevelAfterDiscovering(...)` method to the event decryption method).
https://wearezeta.atlassian.net/browse/SQCORE-539
=> [Fix] Update the conversation security level in the updateEvents decryption method

Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategyTests.swift
It's not possible to view the device list of a federated user
The request to fetch the device list was using a legacy endpoint.
Attempt to use the qualified endpoint when fetching a users's device list.
=> [Fix] Fetching of users clients not happening with qualified endpoint

Sources/Image Preprocessing/ZMImagePreprocessingTrackerTests.m, Sources/Image Preprocessing/ZMImagePreprocessingTrackerTests.swift, Tests/Helpers/NSManagedObjectContext+TestHelpers.h, Tests/Helpers/ZMImagePreprocessingTrackerTests.h, Tests/Resources/Bridging-Header.h, WireRequestStrategy.xcodeproj/project.pbxproj
When building test using XCFramework, link error occurs:
`Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$__TtC13WireDataModel15ZMClientMessage", referenced from:
objc-class-ref in ZMImagePreprocessingTrackerTests.o
ld: symbol(s) not found for architecture x86_64`
Unknown
Convert code contains `ZMClientMessage`  in `ZMImagePreprocessingTrackerTests` to Swift.
=> Fix: XCFramework - Linker error related to ZMClientMessage 

Sources/Object Syncs/Helpers/ProteusMessageSync.swift, Sources/Protocols/SharedProtocols.swift, Sources/Request Strategies/Assets/AssetClientMessageRequestStrategy.swift, Sources/Request Strategies/Assets/AssetClientMessageRequestStrategyTests.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewUpdateRequestStrategy.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewUpdateRequestStrategyTests.swift, Sources/Request Strategies/Client Message/ClientMessageRequestStrategy.swift, Sources/Request Strategies/Client Message/ClientMessageRequestStrategyTests.swift, Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategy.swift, Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategyTests.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift, Sources/Request Strategies/User Clients/ResetSessionRequestStrategy.swift, Sources/Request Strategies/User/UserProfileRequestStrategy.swift, Sources/Request Strategies/User/UserProfileRequestStrategyTests.swift
Introduce a `FederationAware` protocol which can be implemented by request strategies to declare that they interacting with federation endpoints and provide an option to disable their usage.
=> [Feature] Support for disabling federation

WireRequestStrategy.xcodeproj/project.pbxproj
Don't embed the Starscream framework since it will be embedded at the top level.
=> [Chore] Don't embed the Starscream framework

Sources/Request Strategies/Assets/AssetV3UploadRequestStrategy.swift
Asset uploading wouldn't finish when multiple assets were involved, for example video file with a preview image.
In previous refactoring of `AssetV3UploadRequestStrategy` changed `updateUpdatedObject()` to always return `false`, meaning it does not need any do any additional requests, which isn't true when there are multiple assets involved.
Return `true` in case the `processingState` isn't `.done`.
=> [Fix] Asset uploading when multiple assets are needed

Sources/Request Strategies/User/UserProfileRequestStrategy.swift
For large teams / accounts the user profile download would fail.
The backend responded with an error because the query string was too big.
Set the same limit as in the old `ZMUserTranscoder` for how many users we download per request.
=> [Fix] User profile download failing because the query string is too big

Sources/Image Preprocessing/ZMImagePreprocessingTrackerTests.m, Sources/Image Preprocessing/ZMImagePreprocessingTrackerTests.swift
Fix the compiler error on Xcode 13 that `%u` is not allowed for `unsigned` type. ( `imageOwnersThatNeedPreprocessing` is `NSMutableOrderedSet` and should not be casted to unsigned int)
=> Fix: xcode 13 String Format Specifiers %u does not compile

Sources/Object Syncs/Helpers/ProteusMessageSync.swift, Sources/Object Syncs/Helpers/ProteusMessageSyncTests.swift
It's been observed that 1-1 Calls are sometimes not connecting.
If the call message didn't need any further requests for establishing sessions, the SETUP message wouldn't be sent until another event occurred in the application. This behaviour comes from the fact that calling messages are not persisted in Core Data which is what normally triggers the operation loop to send new requests.
Always explicitly tell the operation loop that there's new requests available after scheduling a message to be sent.
This bug was introduced by https://github.com/wireapp/wire-ios-request-strategy/pull/361
=> [Fix] 1-1 Calls sometimes not connecting 

Sources/Request Strategies/User/UserProfileRequestStrategy.swift
The app would crash when syncing the user profiles of your connections.
If a connection is cancelled the `to` field is nulled out and `connections.map(\.to)` would crash due to force unwrapping.
Use `compactMap` instead.
=> [Fix] Don't crash when to field is nil due to connection being cancelled

Sources/Object Syncs/Helpers/ProteusMessageSync.swift, Sources/Object Syncs/Helpers/ProteusMessageSyncTests.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewUpdateRequestStrategyTests.swift, Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategyTests.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift, Sources/Request Strategies/User Clients/ResetSessionRequestStrategyTests.swift
Sending via share extension doesn't work
Share extension attempts to use federation endpoint which require domains but they aren't available.
Disable federation endpoints by default.
Future-work: respect the federation feature flag in the share extension.
=> Fix: Sending via share extension doesn't work

Sources/Object Syncs/Helpers/IdentifierObjectSync.swift, Sources/Other Syncs/DependencyEntitySync.swift, Sources/Protocols/ApplicationStatus.swift
Replace all protocol extends `class` with `AnyObject`
=> Fix: xcode13 warning - Using 'class' keyword to define a class-constrained protocol is deprecated; use 'AnyObject' instead

.github/workflows/semantic-commit-lint.yml
----
----
We want to ensure that PR titles should follow semantic commit rules
Add the semantic commit linter workflow from the Wire's .github repo
N/A
----
----
----
1. E.g. `feature(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.
=> ci: Add Semantic Commit PR title Linter Workflow SQPIT-769

Sources/Request Strategies/Feature configurations/FeatureConfigRequestStrategy.swift, WireRequestStrategy.xcodeproj/xcshareddata/xcschemes/WireRequestStrategy.xcscheme
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1018" title="SQSERVICES-1018" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/secure/viewavatar?size=medium&avatarId=10818&avatarType=issuetype" />SQSERVICES-1018</a>  Revert self-deleting messages
</td></table>
<br />
Another attempt to revert the changes and to find out the reason for the crash.
=> revert: Updating self-deleting messages SQSERVICES-1018

WireRequestStrategy.xcodeproj/project.pbxproj
----
----
By default, Xcode can't find any packages installed by `homebrew` on Apple Silicon Macs, since they're now installed to a different location that isn't on the default $PATH (`/opt/homebrew/bin/`, rather than `/usr/local/bin`).
Workaround: explicitly add this location to `$PATH` before attempting to run `swiftlint`.
----
=> chore: Add support for Apple Silicon brew directory

.github/workflows/jira-lint-and-link.yml
----
----
Setting `fail-when-jira-issue-not-found` to `false` to be in sync with the rest of the repositories. That was the only repo where that parameter inside the workflow  it was set to true.
----
=> chore: Set `fail-when-jira-issue-not-found` to`false` to be in sync with the rest of the repositories

.github/workflows/jira-lint-and-link.yml, .swiftlint.yml, Sources/Helpers/EncryptionSessionDirectory+UpdateEvents.swift, Sources/Helpers/MessageExpirationTimerTests.swift, Sources/Object Syncs/Helpers/IdentifierObjectSyncTests.swift, Sources/Object Syncs/Helpers/InsertedObjectSyncTests.swift, Sources/Object Syncs/Helpers/KeyPathObjectSyncTests.swift, Sources/Object Syncs/Helpers/ModifiedKeyObjectSyncTests.swift, Sources/Other Syncs/DependencyEntitySyncTests.swift, Sources/Payloads/Processing/PayloadProcessing+ConversationTests.swift, Sources/Payloads/Processing/PayloadProcessing+UserProfile.swift, Sources/Payloads/Processing/PayloadProcessing+UserProfileTests.swift, Sources/Protocols/OTREntity.swift, Sources/Request Strategies/Assets/AssetV3UploadRequestStrategyTests.swift, Sources/Request Strategies/Assets/Helpers/AssetsPreprocessor.swift, Sources/Request Strategies/Assets/Helpers/AssetsPreprocessorTests.swift, Sources/Request Strategies/Availability/AvailabilityRequestStrategyTests.swift, Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift, Sources/Request Strategies/Connection/ConnectionRequestStrategy.swift, Sources/Request Strategies/Conversation/ConversationRequestStrategy.swift, Sources/Request Strategies/Conversation/ConversationRequestStrategyTests.swift, Sources/Request Strategies/Delivery Receipts/DeliveryReceiptRequestStrategy.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategyTests.swift, Sources/Request Strategies/User Clients/MissingClientsRequestFactory.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategyTests.swift, Sources/Request Strategies/User Clients/ResetSessionRequestStrategyTests.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategyTests.swift, Tests/Helpers/RequestStrategyTestBase.swift
----
----
With this PR I fix all warnings related to `compiler_protocol_init` and remove the rule from the disabled list.
- **Compiler Protocol Init Violation**: The initializers declared in compiler protocols such as ExpressibleByArrayLiteral shouldn’t be called directly. `compiler_protocol_init`
----
=> fix: SwiftLint warnings for rule `compiler_protocol_init` and remove it from the disabled rules list

.swiftlint.yml, Sources/Request Strategies/Assets/Helpers/LinkAttachmentsPreprocessorTests.swift, Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessorTests.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetDownloadRequestStrategy.swift, Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift, Sources/Request Strategies/Conversation/Actions/UpdateRoleActionHandlerTests.swift
----
----
This PR fixes warnings related to these three SwiftLint rules:
- **Legacy Constructor Violation**: Swift constructors are preferred over legacy convenience functions. `(legacy_constructor)`
- **Unused Closure Parameter Violation**: Unused parameter "syncMOC" in a closure should be replaced with _. `(unused_closure_parameter)`
- **XCTFail Message Violation**: An XCTFail call should include a description of the assertion. `(xctfail_message)`
Last but not least I discovered some indentation and trailing issues in a file and I fixed those too. 
----
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title …
=> fix: SwiftLint warnings for `legacy_constructor`, `unused_closure_parameter` and `xctfail_message`

Sources/Notifications/Push Notifications/Notification Types/Content/ZMLocalNotification.swift, Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Configuration.swift, Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Localization.swift
----
----
Calling notifications were commented out.
This code was moved from sync engine to the request strategy and contains a reference to the `CallState`, which is defined in the sync engine.
Create a local `CallState` which will be passed in from the sync engine side.
----
----
----
=> fix: restore legacy call notifications SQSERVICE-1308

Resources/Base.lproj/Push.strings, Sources/Notifications/Push Notifications/Notification Types/Content/BundledMessageNotificationBuilder.swift, Sources/Notifications/Push Notifications/Notification Types/Content/ZMLocalNotification.swift, Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Configuration.swift, Sources/Notifications/Push Notifications/Notification Types/LocalNotificationType+Localization.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1107" title="SQSERVICES-1107" target="_blank"><img alt="Epic" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10807?size=medium" />SQSERVICES-1107</a>  Notification Service Extension
</td></table>
<br />
----
----
The notification service extension can only display max one notification per push payload, but it's possible that we want to show more than one.
When receiving the push payload, we trigger a fetch of the notification stream, which may return multiple events, each of which generate a local notification.
If there are more than one notification to show, we instead present a single notification for the bundled message events. …
=> feat: add notification for bundled messages SQSERVICES-1107

Sources/Request Strategies/Connection/Actions/ConnectToUserActionHandler.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-517" title="FS-517" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-517</a>  [iOS] Can't send connection request with API versioning
</td></table>
<br />
----
----
With api version v1 and federation disabled, nothing happens when I try to send a connection request.
When using api v1, we use "federation aware" endpoints, which require a domain. When federation is disabled, we don't have any domains stored locally, so we are returning early when trying to create a request.
Add a fallback for getting the local domain via `APIVersion.domain`.
----
----
----
1. …
=> fix: can't send connection request FS-517

Sources/Request Strategies/Client Message/ClientMessageRequestFactory.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategy.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-535" title="FS-535" target="_blank"><img alt="Bug" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10803?size=medium" />FS-535</a>  [iOS] Legal hold regressions
</td></table>
<br />
----
----
In a conversation subject to legal hold, the other (not self) users under legal hold are missing from the legal hold view.
In order to know which users are under legal hold in the conversation, we create a request to fetch the missing clients (using the `ClientMessageRequestFactory`). We then parse the response and update the conversation's legal hold properties accordingly.
The cause of the issue resides in the payload we receive from the backend. …
=> fix: missing users under legal hold in conversation FS-535

.github/workflows/crowdin.yml
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1315" title="SQSERVICES-1315" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQSERVICES-1315</a>  Move Crowdin support from sync engine to request strategy
</td></table>
<br />
----
----
Add a workflow for the GitHub Crowdin action.
----
----
----
=> feat: Add Crowdin github action SQSERVICES-1315

WireRequestStrategy.xcodeproj/xcshareddata/xcschemes/WireRequestStrategy.xcscheme
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/SQSERVICES-1317" title="SQSERVICES-1317" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />SQSERVICES-1317</a>  Re-enabled disabled tests
</td></table>
<br />
----
----
During the implementation of the Notification extension, the `ZMLocalNotificationTests_Message` tests were disabled. We can  re-enable them now. 
----
----
----
=> chore: Re-enable tests SQSERVICES-1317

Sources/Helpers/AssetRequestFactory.swift, Sources/Notifications/NotificationStreamSync.swift, Sources/Request Strategies/User Clients/MissingClientsRequestStrategy.swift
----
----
With this PR we drop the forceVoipSession because it has been deprecated and we can't use it anymore.
----
=> chore: Drop forceVoipSession

Sources/Request Strategies/Connection/Actions/UpdateConnectionActionHandler.swift, Sources/Request Strategies/Connection/Actions/UpdateConnectionActionHandlerTests.swift
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-801" title="FS-801" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-801</a>  [iOS] Bring back PUT endpoint for /connections
</td></table>
<br />
----
----
`PUT /connections/:domain/:user` was restored for v2, which is the same behavior for v1, so I removed the change we made earlier.
----
----
----
=> chore: restore PUT /connection/:domain/:user FS-801

Sources/Helpers/ZMTransportResponse+ErrorInfo.swift, Sources/Notifications/CallEventContent.swift, Sources/Notifications/CallEventContentTests.swift, Sources/Object Syncs/Helpers/MLSMessage.swift, Sources/Object Syncs/Helpers/MessageSync.swift, Sources/Payloads/Payload+Decoding.swift, Sources/Payloads/Payload.swift, Sources/Request Strategies/User Clients/FetchUserClientsAction.swift, Sources/Request Strategies/User Clients/FetchUserClientsActionHandler.swift, Sources/Request Strategies/User Clients/FetchUserClientsActionHandlerTests.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-675" title="FS-675" target="_blank"><img alt="Task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10818?size=medium" />FS-675</a>  [iOS] Distribute CONFKEY to all members of conversation [temp-M4]
</td></table>
<br />
----
----
Sending of calling messages happens in the sync engine. In order to send call messages in an MLS group, we need to use `MessageSync`, which is currently internal. This PR opens the access to `public`.
Additionally, we also need to determine the type of call message, particularly if it is a conference key or a reject message. This PR also adds helper methods to `CallEventContent`. 
We also add the caller client id …
=> feat(mls): support calling in MLS groups FS-675

Sources/Notifications/CallEventContent.swift, Sources/Notifications/Push Notifications/Notification Types/Helpers/ZMLocalNotificationSet.swift
----
----
Add `isVideo` property to the CallEventContent.
----
----
----
=> feat: Add isVideo property to the CallEventContent

Sources/Notifications/CallEventContent.swift, Sources/Notifications/Push Notifications/Notification Types/Helpers/ZMLocalNotificationSet.swift, Sources/Notifications/VoIPPushHelper.swift, Sources/Synchronization/Decoding/EventDecoder.swift, Sources/Synchronization/Decoding/StoreUpdateEvent.swift
----
----
Add `isIncomingCall`, `isAnsweredElsewhere`, `isRegected` properties to `CallEventContent`.
----
----
----
=> fix: Add additional properties to CallEventContent
