WireRequestStrategy.xcodeproj/project.pbxproj, WireRequestStrategy/Helper/AssetRequestFactory.swift, WireRequestStrategy/Helper/ZMAssetRequestFactory.h, WireRequestStrategy/Helper/ZMAssetRequestFactory.m, WireRequestStrategy/StatusProtocols/SharedProtocols.swift, WireRequestStrategy/WireRequestStrategy.h
*In this PR*
We need to move additional files as well as some protocol declaration into this framework since these are accessed by message transcoders and non-message transcoders
=> Move additional shared files

WireRequestStrategy/ZMUpstreamAssetSync.m
We need to create a `ZMUpstreamAssetSync` and pass in a filter. This is not possible with the current `init`
=> Simplify ZMUpstreamAssetSync ctor

WireRequestStrategy.xcodeproj/xcshareddata/xcschemes/WireRequestStrategy.xcscheme
Enable Core Data threading debugging for all tests
=> Enable core data debugging for tests

WireRequestStrategy/DependencyEntitySync.swift
=> Add dependency logs

WireRequestStrategy/ZMSingleRequestSync.h
Bringing SingleRequestSync to the 21st century
=> Annotated SingleRequestSync API with optionality hints

WireRequestStrategy.xcodeproj/project.pbxproj, WireRequestStrategyTests/WireRequestStrategyTestHost/AppDelegate.swift, WireRequestStrategyTests/WireRequestStrategyTestHost/Info.plist
This is one of few frameworks that do not run test bundle inside a host application. This make a difference when we want to access things that are generally available in an application (shared container, main bundle etc).
=> Adding test host

Sources/Helpers/AssetRequestFactory.swift, Sources/Request Strategies/Client Message/ClientMessageRequestFactoryTests.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoder.swift, Sources/Request Strategies/Client Message/ClientMessageTranscoderTests+MessageConfirmation.swift, Sources/Request Strategies/Generic Message/GenericMessageRequestStrategyTests.swift, Tests/Helpers/MessagingTestBase.swift
=> Update for API changes

Sources/Request Strategies/Assets/Helpers/LinkPreviewPreprocessor.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewAssetUploadRequestStrategy.swift, Sources/Request Strategies/Assets/Link Preview/LinkPreviewUploadRequestStrategy.swift
Adjust link preview logging to be more expressive.
=> Adjust and unify link preview logging

Sources/Request Strategies/Properties/UserPropertyRequestStrategy.swift, Sources/Request Strategies/Properties/UserPropertyRequestStrategyTests.swift
The permanent error case was not really handled.
=> Fix: request loop on property 404

Sources/Request Strategies/User/UserRichProfileRequestStrategy.swift, Sources/Request Strategies/User/UserRichProfileRequestStrategyTests.swift
When backend has the feature deployed we can safely remove testing code.
=> Rich profile: remove test code

Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift, Sources/Request Strategies/User Clients/FetchingClientRequestStrategyTests.swift
A message (like reaction) wouldn't get sent.
The message was waiting some client metadata to be fetched before it could be sent. The fetching of the client metadata never completed because the backend responded with 404 since the clients had been deleted.
Delete clients when backend informs us that they no longer exists.
=> Delete client & session if BE tells us it doesn't exist anymore

Sources/Protocols/OTREntity.swift, Sources/Request Strategies/User Clients/VerifyLegalHoldRequestStrategyTests.swift
When verifying a legal hold we send an empty message in the conversation to get an updated list of the active clients in the conversation. Because we send an empty message the response will always be a list of missing clients: 
```
missing: {
user1: [ client1, client2]
user2: [ client1]
}
```
This list represents the currently active user and clients in the conversation, we need to perform diff against our local state to figure which clients have been deleted or added. If a user is present locally but missing from the response it can mean two things:
1. User has been removed from the group and we are not aware of it
2. User has deleted all his/her clients 
We decided to always treat it as 2.
Delete all locally known clients when user is not appearing in the missing map.
=> Fix missing edge case when verifying legal hold

Sources/Request Strategies/MLS/MLSRequestStrategy.swift, Sources/Request Strategies/MLS/MLSStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-692" title="FS-692" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-692</a>  [iOS] Create `MLSRequestStrategy`
</td></table>
<br />
----
----
Create `MLSStrategy` which will hold all the action handlers for the new mls endpoints. There are currently no action handlers yet, but we will add them in future PRs.
- We will add integration tests as we add handlers. Currently this class has no behavior to test.
----
----
----
1. E.g. `feat(conversation-list): Sort conversations by most …
=> chore: create MLSStrategy FS-692

Sources/Helpers/String+Empty.swift, Sources/Request Strategies/MLS/Actions/ClaimMLSKeyPackageAction.swift, Sources/Request Strategies/MLS/Actions/ClaimMLSKeyPackageActionHandler.swift, Sources/Request Strategies/MLS/Actions/ClaimMLSKeyPackageActionHandlerTests.swift, Sources/Request Strategies/MLS/MLSRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-693" title="FS-693" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-693</a>  [iOS] Create `ClaimMLSKeyPackageAction`
</td></table>
<br />
----
----
- Created the action & action handler to claim MLS key packages
- Added action handler to the `MLSRequestStrategy`
----
----
----
=> feat(mls): create action to claim key packages - FS-693

Sources/Request Strategies/MLS/Actions/UploadSelfMLSKeyPackagesAction.swift, Sources/Request Strategies/MLS/Actions/UploadSelfMLSKeyPackagesActionHandler.swift, Sources/Request Strategies/MLS/Actions/UploadSelfMLSKeyPackagesActionHandlerTests.swift, Sources/Request Strategies/MLS/MLSRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-694" title="FS-694" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-694</a>  [iOS] Create `UploadSelfMLSKeyPackagesAction`
</td></table>
<br />
----
----
- Created `UploadSelfMLSKeyPackagesAction`
- Created `UploadSelfMLSKeyPackagesActionHandler`
- Added action handler to `MLSRequestStrategy`
----
----
----
=> feat(mls): add action for self key package upload FS-694

Sources/Request Strategies/MLS/Actions/SendMLSWelcomeAction.swift, Sources/Request Strategies/MLS/Actions/SendMLSWelcomeActionHandler.swift, Sources/Request Strategies/MLS/Actions/SendMLSWelcomeActionHandlerTests.swift, Sources/Request Strategies/MLS/MLSRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-697" title="FS-697" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-697</a>  [iOS] Create `SendMLSWelcomeAction`
</td></table>
<br />
----
----
- Created `SendMLSWelcomeAction`
- Created `SendMLSWelcomeActionHandler`
- Added action handler to `MLSRequestStrategy`
----
----
----
=> feat(mls): add action to send MLS welcome FS-697

Sources/Request Strategies/MLS/Actions/CountSelfMLSKeyPackagesAction.swift, Sources/Request Strategies/MLS/Actions/CountSelfMLSKeyPackagesActionHandler.swift, Sources/Request Strategies/MLS/Actions/CountSelfMLSKeyPackagesActionHandlerTests.swift, Sources/Request Strategies/MLS/MLSRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-695" title="FS-695" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-695</a>  [iOS] Create `CountSelfMLSKeyPackagesAction`
</td></table>
<br />
----
----
- Created an action `CountSelfMLSKeyPackagesAction` for counting the number or remaining key packages for the self user.
- Created an action handler `CountSelfMLSKeyPackagesActionHandler` for `CountSelfMLSKeyPackagesAction`.
- Added the action handler to the `MLSRequestStrategy`.
----
----
----
1. E.g. `feat(conversation-list): …
=> feat(mls): key package count action for self user FS-695

Sources/Request Strategies/MLS/Actions/SendMLSMessagesAction.swift, Sources/Request Strategies/MLS/Actions/SendMLSMessagesActionHandler.swift, Sources/Request Strategies/MLS/Actions/SendMLSMessagesActionHandlerTests.swift, Sources/Request Strategies/MLS/MLSRequestStrategy.swift, WireRequestStrategy.xcodeproj/project.pbxproj
<table>
<td>
<a href="https://wearezeta.atlassian.net/browse/FS-696" title="FS-696" target="_blank"><img alt="Sub-task" src="https://wearezeta.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10816?size=medium" />FS-696</a>  [iOS] Create `SendMLSMessageAction`
</td></table>
<br />
----
----
- Created an action `SendMLSMessagesAction` for counting the number or remaining key packages for the self user.
- Created an action handler `SendMLSMessagesActionHandler` for `SendMLSMessagesAction`.
- Added the action handler to the `SendMLSMessagesActionHandlerTests`.
- Added tests for SendMLSMessagesActionHandler
----
----
----
1. E.g. …
=> feat(mls): send MLS message action FS-696

Sources/Request Strategies/User Clients/FetchingClientRequestStrategy.swift
----
----
For API version 2, we can't fetch other users clients.
Both the request payload and the response payload was incorrect.
Fix the payload structure.
The fetching clients request strategy tests are disabled (not sure why). I tried to fix them the but it'll take a lot more effort. I've added it as a todo that we can return to.
----
----
----
=> fix: cannot fetch clients on api v2

Sources/Object Syncs/Helpers/MLSMessageSync.Transcoder.swift, Sources/Payloads/Processing/Helpers/MLSEventProcessor.swift, Sources/Payloads/Processing/PayloadProcessing+Conversation.swift, Sources/Request Strategies/Conversation/ConversationRequestStrategy.swift, Sources/Synchronization/Decoding/EventDecoder.swift
----
----
Improve logging by:
- adding more logs
- adding more context to existing logs
- using only the mls log tag
----
----
----
=> chore(mls): improve logging
